version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: distance-calculator
  wildfly:
    depends_on:
      - db
    image: jboss/wildfly:10.1.0.Final
    volumes:
      - ./jee-test.war:/opt/jboss/wildfly/standalone/deployments/jee-test.war
    ports:
      - "8080:8080"
      - "8787:8787"
    entrypoint: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 --debug
    restart: always
volumes:
  db_data: {}